prometheus:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/use-regex: "true"
      cert-manager.io/cluster-issuer: letsencrypt-prod
      cert-manager.io/acme-challenge-type: http01
    hosts:
      - prometheus.cauchy.link
    path: /
    pathType: Prefix
    tls:
      - secretName: letsencrypt-prometheus
        hosts:
          - prometheus.cauchy.link
  serverFiles:
    prometheus.yml:
      scrape_configs:
        - job_name: minio-job
          metrics_path: /minio/v2/metrics/cluster
          scheme: http
          static_configs:
            - targets:
                - minio.minio.svc.cluster.local:9000

alertmanager:
  enabled: false

grafana:
  enabled: true
  defaultDashboardsTimezone: utc
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/use-regex: "true"
      cert-manager.io/cluster-issuer: letsencrypt-prod
      cert-manager.io/acme-challenge-type: http01
    hosts:
      - grafana.cauchy.link
    path: /
    pathType: Prefix
    tls:
      - secretName: letsencrypt-prod
        hosts:
          - grafana.cauchy.link
  sidecar:
    datasources:
      url: http://prometheus-kube-prometheus-prometheus.prometheus.svc.cluster.local:9090
