apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: github-elixir
  namespace: argo-events
spec:
  service:
    ports:
      - port: 12000
        targetPort: 12000
  github:
    elixir:
      repositories:
        - owner: erikperkins
          names:
            - pascal
      webhook:
        endpoint: /push
        port: "12000"
        method: POST
        url: http://argo.cauchy.link/webhook/github/elixir
      events:
        - "push"
      apiToken:
        name: github-access
        key: token
      insecure: true
      active: true
      contentType: json
---
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: github-elixir-sensor
  namespace: argo-events
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: elixir-push
      eventSourceName: github-elixir
      eventName: elixir
  triggers:
    - template:
        conditions: elixir-push
        name: elixir-workflow-trigger
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: github-elixir-
              spec:
                arguments:
                  parameters:
                    - name: repository
                      value: "organisation/repository"
                    - name: git_sha
                      value: "commit"
                    - name: tag
                      value: "tag"
                    - name: organisation
                      value: "organisation"
                    - name: app_repo
                      value: "repo"
                    - name: branch
                      value: "branch"
                workflowTemplateRef:
                  name: elixir
          parameters:
            - src:
                dependencyName: elixir-push
                dataKey: body.repository.full_name
              dest: spec.arguments.parameters.0.value
            - src:
                dependencyName: elixir-push
                dataKey: body.after
              dest: spec.arguments.parameters.1.value
            - src:
                dependencyName: elixir-push
                dataTemplate: "{{.Input.body.after | substr 0 7}}"
              dest: spec.arguments.parameters.2.value
            - src:
                dependencyName: elixir-push
                dataTemplate: "{{.Input.body.repository.full_name | splitList \"/\" | first}}"
              dest: spec.arguments.parameters.3.value
            - src:
                dependencyName: elixir-push
                dataTemplate: "{{.Input.body.repository.full_name | splitList \"/\" | last}}"
              dest: spec.arguments.parameters.4.value
            - src:
                dependencyName: elixir-push
                dataTemplate: "{{.Input.body.ref | splitList \"/\" | last}}"
              dest: spec.arguments.parameters.5.value