apiVersion: batch/v1
kind: Job
metadata:
  name: debug
spec:
  ttlSecondsAfterFinished: 1
  template:
    spec:
      containers:
        - name: ubuntu
          image: ubuntu
          command:
            - sleep
            - 1d
      restartPolicy: Never
  backoffLimit: 1
