apiVersion: v1
kind: Namespace
metadata:
  name: babinet
  labels:
    name: babinet
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: babinet
  name: babinet
  namespace: babinet
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: babinet
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: babinet
data:
  default.conf: |
    server {
      listen 80;
      root /usr/share/nginx/html;
      location / {
          try_files $uri @wsgi;
      }
      location @wsgi {
          include uwsgi_params;
          uwsgi_pass unix:/tmp/uwsgi.socket;
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: babinet
  name: babinet
  namespace: babinet
spec:
  replicas: 2
  selector:
    matchLabels:
      app: babinet
  template:
    metadata:
      labels:
        app: babinet
    spec:
      containers:
        - image: erikperkins/babinet:latest
          name: babinet
          volumeMounts:
            - name: uwsgi-socket
              mountPath: /tmp
        - image: nginx:1.23.3-alpine-slim
          name: nginx
          volumeMounts:
            - name: uwsgi-socket
              mountPath: /tmp
            - name: conf
              mountPath: /etc/nginx/conf.d/
          ports:
            - containerPort: 80
      volumes:
        - name: uwsgi-socket
        - name: conf
          configMap:
            name: nginx-conf
