apiVersion: v1
kind: Namespace
metadata:
  name: mer
  labels:
    name: mer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mariotte
  name: mariotte
  namespace: mer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariotte
  template:
    metadata:
      labels:
        app: mariotte
    spec:
      containers:
        - image: erikperkins/mariotte:latest
          name: mariotte
          securityContext:
            allowPrivilegeEscalation: true
