apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argo
  namespace: argo-events
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: argo.cauchy.link
      http:
        paths:
          - path: /webhook/github/elixir(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: github-elixir-eventsource-svc
                port:
                  number: 12000
          - path: /webhook/github/python(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: github-python-eventsource-svc
                port:
                  number: 12000
---
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: github-elixir
  namespace: argo-events
spec:
  service:
    ports:
      - port: 12000
        targetPort: 12000
  github:
    elixir:
      repositories:
        - owner: erikperkins
          names:
            - pascal
      webhook:
        endpoint: /push
        port: "12000"
        method: POST
        url: http://argo.cauchy.link/webhook/github/elixir
      events:
        - "push"
      apiToken:
        name: github-access
        key: token
      insecure: true
      active: true
      contentType: json
---
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: github-python
  namespace: argo-events
spec:
  service:
    ports:
      - port: 12000
        targetPort: 12000
  github:
    python:
      repositories:
        - owner: erikperkins
          names:
            - babinet
      webhook:
        endpoint: /push
        port: "12000"
        method: POST
        url: http://argo.cauchy.link/webhook/github/python
      events:
        - "push"
      apiToken:
        name: github-access
        key: token
      insecure: true
      active: true
      contentType: json
---
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook
  namespace: argo-events
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: elixir-push
      eventSourceName: github-elixir
      eventName: elixir
    - name: python-push
      eventSourceName: github-python
      eventName: python
  triggers:
    - template:
        conditions: elixir-push
        name: elixir-workflow-trigger
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: github-elixir-
              spec:
                arguments:
                  parameters:
                    - name: repository
                      value: "organisation/repository"
                    - name: git_sha
                      value: "commit"
                    - name: tag
                      value: "tag"
                    - name: organisation
                      value: "organisation"
                    - name: app_repo
                      value: "repo"
                workflowTemplateRef:
                  name: elixir
          parameters:
            - src:
                dependencyName: elixir-push
                dataKey: body.repository.full_name
              dest: spec.arguments.parameters.0.value
            - src:
                dependencyName: elixir-push
                dataKey: body.after
              dest: spec.arguments.parameters.1.value
            - src:
                dependencyName: elixir-push
                dataTemplate: "{{.Input.body.after | substr 0 7}}"
              dest: spec.arguments.parameters.2.value
            - src:
                dependencyName: elixir-push
                dataTemplate: "{{.Input.body.repository.full_name | splitList \"/\" | first}}"
              dest: spec.arguments.parameters.3.value
            - src:
                dependencyName: elixir-push
                dataTemplate: "{{.Input.body.repository.full_name | splitList \"/\" | last}}"
              dest: spec.arguments.parameters.4.value
    - template:
        conditions: python-push
        name: python-workflow-trigger
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: github-python-
              spec:
                arguments:
                  parameters:
                    - name: repository
                      value: "organisation/repository"
                    - name: git_sha
                      value: "commit"
                    - name: tag
                      value: "tag"
                    - name: organisation
                      value: "organisation"
                    - name: app_repo
                      value: "repo"
                workflowTemplateRef:
                  name: python
          parameters:
            - src:
                dependencyName: python-push
                dataKey: body.repository.full_name
              dest: spec.arguments.parameters.0.value
            - src:
                dependencyName: python-push
                dataKey: body.after
              dest: spec.arguments.parameters.1.value
            - src:
                dependencyName: python-push
                dataTemplate: "{{.Input.body.after | substr 0 7}}"
              dest: spec.arguments.parameters.2.value
            - src:
                dependencyName: python-push
                dataTemplate: "{{.Input.body.repository.full_name | splitList \"/\" | first}}"
              dest: spec.arguments.parameters.3.value
            - src:
                dependencyName: python-push
                dataTemplate: "{{.Input.body.repository.full_name | splitList \"/\" | last}}"
              dest: spec.arguments.parameters.4.value