apiVersion: v1
kind: Namespace
metadata:
  name: jupyter
---
apiVersion: v1
kind: Service
metadata:
  name: jupyter
  namespace: jupyter
spec:
  ports:
    - name: http
      port: 8888
      targetPort: 8888
  selector:
    app: jupyter
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter
  namespace: jupyter
spec:
  selector:
    matchLabels:
      app: jupyter
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jupyter
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: jupyter
          image: jupyter/minimal-notebook
          imagePullPolicy: IfNotPresent
          env:
            - name: JUPYTER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: jupyter
                  key: password
          ports:
            - containerPort: 8888
          volumeMounts:
            - name: jupyter
              mountPath: /home/jovyan/work
              subPath: work
      volumes:
        - name: jupyter
          persistentVolumeClaim:
            claimName: jupyter
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jupyter
  namespace: jupyter
  labels:
    type: local
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jupyter
  namespace: jupyter
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jupyter
  namespace: jupyter
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    cert-manager.io/acme-challenge-type: http01
spec:
  tls:
    - hosts:
        - jupyter.cauchy.link
      secretName: letsencrypt-prod
  rules:
    - host: jupyter.cauchy.link
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jupyter
                port:
                  name: http
