apiVersion: v1
kind: Namespace
metadata:
  name: pascal
---
apiVersion: v1
kind: Service
metadata:
  name: pascal
  namespace: pascal
  labels:
    app: pascal
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 4000
  selector:
    app: pascal
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pascal
  namespace: pascal
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: pascal
  template:
    metadata:
      labels:
        app: pascal
    spec:
      containers:
        - name: pascal
          image: erikperkins/pascal:latest
          imagePullPolicy: Always
          env:
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: pascal-secret-key-base
                  key: secretKeyBase
          ports:
            - containerPort: 4000
---
apiVersion: v1
kind: Secret
metadata:
  name: pascal
  namespace: pascal
type: Opaque
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pascal
  namespace: pascal
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
        - cauchy.link
      secretName: pascal-secret
  rules:
    - host: cauchy.link
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pascal
                port:
                  name: http
